[package]
name = "day16"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
common = { version = "0.1.0", path = "../common" }
itertools = "0.10.5"
nom = "7.1.1"
rand = "0.8.5"
tqdm = "0.4.2"
